
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/ncs/toolchains/936afb6332/opt/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:22 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/ncs/toolchains/936afb6332/opt/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:22 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/ncs/toolchains/936afb6332/"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/"
      - "C:/ncs/toolchains/936afb6332/bin/"
      - "C:/ncs/toolchains/936afb6332/opt/bin/"
      - "C:/ncs/toolchains/936afb6332/opt/bin/Scripts/"
      - "C:/ncs/toolchains/936afb6332/opt/nanopb/generator-bin/"
      - "C:/ncs/toolchains/936afb6332/nrfutil/bin/"
      - "C:/ncs/toolchains/936afb6332/opt/zephyr-sdk/arm-zephyr-eabi/bin/"
      - "C:/ncs/toolchains/936afb6332/opt/zephyr-sdk/riscv64-zephyr-elf/bin/"
      - "C:/Users/USER/.nrfutil/lib/nrfutil-toolchain-manager/"
      - "C:/Program Files/Python313/Scripts/"
      - "C:/Program Files/Python313/"
      - "C:/Program Files (x86)/Common Files/Oracle/Java/javapath/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "D:/tools/adb/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files (x86)/Qualcomm/QIKTool/1.0.108.1/"
      - "C:/Program Files/nodejs/"
      - "C:/Users/USER/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Program Files (x86)/vbee/"
      - "C:/Users/USER/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/USER/AppData/Roaming/npm/"
      - "C:/Users/USER/.vscode/extensions/ms-python.debugpy-2026.6.0-win32-x64/bundled/scripts/noConfigScripts/"
      - "C:/Users/USER/AppData/Roaming/Code/User/globalStorage/github.copilot-chat/debugCommand/"
    searched_directories:
      - "C:/ncs/toolchains/936afb6332/ninja-build.com"
      - "C:/ncs/toolchains/936afb6332/ninja-build.exe"
      - "C:/ncs/toolchains/936afb6332/ninja-build"
      - "C:/ncs/toolchains/936afb6332/ninja.com"
      - "C:/ncs/toolchains/936afb6332/ninja.exe"
      - "C:/ncs/toolchains/936afb6332/ninja"
      - "C:/ncs/toolchains/936afb6332/samu.com"
      - "C:/ncs/toolchains/936afb6332/samu.exe"
      - "C:/ncs/toolchains/936afb6332/samu"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/ninja-build.com"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/ninja-build.exe"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/ninja-build"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/ninja.com"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/ninja.exe"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/ninja"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/samu.com"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/samu.exe"
      - "C:/ncs/toolchains/936afb6332/mingw64/bin/samu"
      - "C:/ncs/toolchains/936afb6332/bin/ninja-build.com"
      - "C:/ncs/toolchains/936afb6332/bin/ninja-build.exe"
      - "C:/ncs/toolchains/936afb6332/bin/ninja-build"
      - "C:/ncs/toolchains/936afb6332/bin/ninja.com"
      - "C:/ncs/toolchains/936afb6332/bin/ninja.exe"
      - "C:/ncs/toolchains/936afb6332/bin/ninja"
      - "C:/ncs/toolchains/936afb6332/bin/samu.com"
      - "C:/ncs/toolchains/936afb6332/bin/samu.exe"
      - "C:/ncs/toolchains/936afb6332/bin/samu"
      - "C:/ncs/toolchains/936afb6332/opt/bin/ninja-build.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/ninja-build.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/ninja-build"
      - "C:/ncs/toolchains/936afb6332/opt/bin/ninja.com"
    found: "C:/ncs/toolchains/936afb6332/opt/bin/ninja.exe"
    search_context:
      ENV{PATH}:
        - "C:\\ncs\\toolchains\\936afb6332"
        - "C:\\ncs\\toolchains\\936afb6332\\mingw64\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\bin\\Scripts"
        - "C:\\ncs\\toolchains\\936afb6332\\opt/nanopb/generator-bin"
        - "C:\\ncs\\toolchains\\936afb6332\\nrfutil\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\zephyr-sdk\\arm-zephyr-eabi\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\zephyr-sdk\\riscv64-zephyr-elf\\bin"
        - "C:\\Users\\USER\\.nrfutil\\lib\\nrfutil-toolchain-manager"
        - "C:\\Program Files\\Python313\\Scripts"
        - "C:\\Program Files\\Python313"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\WINDOWS\\System32\\OpenSSH"
        - "D:\\tools\\adb"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files (x86)\\Qualcomm\\QIKTool\\1.0.108.1"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\USER\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files (x86)\\vbee"
        - "C:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\USER\\AppData\\Roaming\\npm"
        - "c:\\Users\\USER\\.vscode\\extensions\\ms-python.debugpy-2026.6.0-win32-x64\\bundled\\scripts\\noConfigScripts"
        - "c:\\Users\\USER\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
  -
    kind: "find-v1"
    backtrace:
      - "C:/ncs/toolchains/936afb6332/opt/share/cmake-4.2/Modules/FindPython/Support.cmake:2437 (find_program)"
      - "C:/ncs/toolchains/936afb6332/opt/share/cmake-4.2/Modules/FindPython3.cmake:671 (include)"
      - "C:/ncs/v3.3.0/zephyr/cmake/modules/python.cmake:41 (find_package)"
      - "C:/ncs/v3.3.0/zephyr/cmake/modules/user_cache.cmake:30 (include)"
      - "C:/ncs/v3.3.0/zephyr/cmake/modules/extensions.cmake:5 (include)"
      - "cmake/modules/sysbuild_default.cmake:8 (include)"
      - "C:/ncs/v3.3.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include)"
      - "C:/ncs/v3.3.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "C:/ncs/v3.3.0/zephyr/share/sysbuild-package/cmake/SysbuildConfig.cmake:8 (include)"
      - "template/CMakeLists.txt:10 (find_package)"
    mode: "program"
    variable: "_Python3_EXECUTABLE_DEBUG"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "python3.12_d"
      - "python3_d"
      - "python_d"
    candidate_directories:
      - "C:/ncs/toolchains/936afb6332/opt/bin/"
    searched_directories:
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.12_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.12_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.12_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python_d"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\ncs\\toolchains\\936afb6332"
        - "C:\\ncs\\toolchains\\936afb6332\\mingw64\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\bin\\Scripts"
        - "C:\\ncs\\toolchains\\936afb6332\\opt/nanopb/generator-bin"
        - "C:\\ncs\\toolchains\\936afb6332\\nrfutil\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\zephyr-sdk\\arm-zephyr-eabi\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\zephyr-sdk\\riscv64-zephyr-elf\\bin"
        - "C:\\Users\\USER\\.nrfutil\\lib\\nrfutil-toolchain-manager"
        - "C:\\Program Files\\Python313\\Scripts"
        - "C:\\Program Files\\Python313"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\WINDOWS\\System32\\OpenSSH"
        - "D:\\tools\\adb"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files (x86)\\Qualcomm\\QIKTool\\1.0.108.1"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\USER\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files (x86)\\vbee"
        - "C:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\USER\\AppData\\Roaming\\npm"
        - "c:\\Users\\USER\\.vscode\\extensions\\ms-python.debugpy-2026.6.0-win32-x64\\bundled\\scripts\\noConfigScripts"
        - "c:\\Users\\USER\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
      CMAKE_INSTALL_PREFIX: "C:/Program Files (x86)/sysbuild_toplevel"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "C:/Program Files"
        - "C:/Program Files (x86)"
        - "C:/ncs/toolchains/936afb6332/opt"
        - "C:/Program Files (x86)/sysbuild_toplevel"
...

---
events:
  -
    kind: "find-v1"
    backtrace:
      - "C:/ncs/toolchains/936afb6332/opt/share/cmake-4.2/Modules/FindPython/Support.cmake:2437 (find_program)"
      - "C:/ncs/toolchains/936afb6332/opt/share/cmake-4.2/Modules/FindPython3.cmake:671 (include)"
      - "C:/ncs/v3.3.0/zephyr/cmake/modules/python.cmake:41 (find_package)"
      - "C:/ncs/v3.3.0/zephyr/cmake/modules/user_cache.cmake:30 (include)"
      - "C:/ncs/v3.3.0/zephyr/cmake/modules/extensions.cmake:5 (include)"
      - "cmake/modules/sysbuild_default.cmake:8 (include)"
      - "C:/ncs/v3.3.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:75 (include)"
      - "C:/ncs/v3.3.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)"
      - "C:/ncs/v3.3.0/zephyr/share/sysbuild-package/cmake/SysbuildConfig.cmake:8 (include)"
      - "template/CMakeLists.txt:10 (find_package)"
    mode: "program"
    variable: "_Python3_EXECUTABLE_DEBUG"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "python3.15_d"
      - "python3.14_d"
      - "python3.13_d"
      - "python3.12_d"
      - "python3.11_d"
      - "python3.10_d"
      - "python3_d"
      - "python_d"
    candidate_directories:
      - "C:/ncs/toolchains/936afb6332/opt/bin/"
    searched_directories:
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.15_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.15_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.15_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.14_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.14_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.14_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.13_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.13_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.13_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.12_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.12_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.12_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.11_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.11_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.11_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.10_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.10_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3.10_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python3_d"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python_d.com"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python_d.exe"
      - "C:/ncs/toolchains/936afb6332/opt/bin/python_d"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\ncs\\toolchains\\936afb6332"
        - "C:\\ncs\\toolchains\\936afb6332\\mingw64\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\bin\\Scripts"
        - "C:\\ncs\\toolchains\\936afb6332\\opt/nanopb/generator-bin"
        - "C:\\ncs\\toolchains\\936afb6332\\nrfutil\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\zephyr-sdk\\arm-zephyr-eabi\\bin"
        - "C:\\ncs\\toolchains\\936afb6332\\opt\\zephyr-sdk\\riscv64-zephyr-elf\\bin"
        - "C:\\Users\\USER\\.nrfutil\\lib\\nrfutil-toolchain-manager"
        - "C:\\Program Files\\Python313\\Scripts"
        - "C:\\Program Files\\Python313"
        - "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0"
        - "C:\\WINDOWS\\System32\\OpenSSH"
        - "D:\\tools\\adb"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files (x86)\\Qualcomm\\QIKTool\\1.0.108.1"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\USER\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files (x86)\\vbee"
        - "C:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\USER\\AppData\\Roaming\\npm"
        - "c:\\Users\\USER\\.vscode\\extensions\\ms-python.debugpy-2026.6.0-win32-x64\\bundled\\scripts\\noConfigScripts"
        - "c:\\Users\\USER\\AppData\\Roaming\\Code\\User\\globalStorage\\github.copilot-chat\\debugCommand"
      CMAKE_INSTALL_PREFIX: "C:/Program Files (x86)/sysbuild_toplevel"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "C:/Program Files"
        - "C:/Program Files (x86)"
        - "C:/ncs/toolchains/936afb6332/opt"
        - "C:/Program Files (x86)/sysbuild_toplevel"
...
